config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  resources :users do
    resources :leads
  end
  resources :companies


  get '/signin', to: 'sessions#new'
  post '/sessions/create', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  get '/auth/github/callback' => 'sessions#create_oath'

  get '/web_dev' => 'leads#web_dev'

  get '/search' => 'leads#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :leads
  has_many :users, through: :leads

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
  belongs_to :company

  validates :position, presence: true
  validates :phone_number, numericality: true

  accepts_nested_attributes_for :company

    scope :search, ->(search_term) { where("position == ?", search_term) }

  def company_attributes=(company_attributes)
    company = Company.find_or_create_by(name: company_attributes[:name])
    company.update(company_attributes)
    self.company_id = company.id
  end

  OPTIONS = [
      {:name => 'Warm', :id => 1},
      {:name => 'Cold', :id => 2},
    ]

    def self.options
      OPTIONS.map{ |option| [option[:name], option[:id]] }
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :leads
  has_many :companies, through: :leads

  validates :email, uniqueness: { case_sensitive: false }
  validates :username, uniqueness: { case_sensitive: false }
  validates :username, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user

  before_action :require_logged_in, except: [:new, :create, :home, :create_oath]

  def logged_in?
    !!current_user
  end

  private

  def require_logged_in
    redirect_to root_path unless logged_in?
  end

  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def show
  end
  
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_user
  before_action :set_lead, only: [:edit, :update, :destroy]

  def index
    if current_user
      @leads = @user.leads
    else
      redirect_to root_path
    end
  end

  def new
    @lead = Lead.new(user_id: params[:user_id])
    @company = Company.new
  end

  def create

    if params[:lead][:company_id].present?
      @company = Company.find_by(id: params[:lead][:company_id])
      @lead = Lead.create(existing_lead_params)
    else
      @company = Company.create(params[:company_attributes])
      @lead = Lead.create(lead_params)
    end

    if @lead.save
      redirect_to user_leads_url(@user)
    else
      render :new
    end
  end

  def edit
    set_lead
  end

  def update
    set_lead
    if @lead.update(lead_params)
      redirect_to user_leads_url(@user)
    else
      render :edit
    end
  end

  def search
    #receive the param of the search
    if params[:search]
      @leads = current_user.leads.search(params[:search])
    else
      @leads = current_user.leads
    end
  end

  def destroy
    @lead.destroy
    redirect_to user_leads_url(@user)
  end



  private

  helper_method :set_user
    def set_user
      @user = User.find(session[:user_id])
    end

    def set_lead
      @lead = Lead.find(params[:id])
    end

    def lead_params
      params.require(:lead).permit(
        :user_id,
        :status,
        :point_person,
        :phone_number,
        :email,
        :position,
        :created_on,
        :applied_on,
        company_attributes: [:name, :description, :website, :city]
      )
    end

    def existing_lead_params
      params.require(:lead).permit(
        :user_id,
        :status,
        :point_person,
        :phone_number,
        :email,
        :position,
        :created_on,
        :applied_on,
        :company_id
      )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    @users = User.all
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      session[:user_id] = @user.id
      redirect_to user_leads_url(@user)
    else
      render :new
    end
  end

  def create_oath
    puts auth
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.username = auth['info']['nickname']
      u.email = auth['info']['email']
    end
    @user.save!(:validate => false)
    session[:user_id] = @user.id
    redirect_to user_leads_url(@user)
  end


  def destroy
    session.delete :user_id
    redirect_to root_url
  end

  private

    def auth
      request.env["omniauth.auth"]
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  private

  helper_method :set_user
    def set_user
      @user = User.find(session[:user_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_leads_url(@user), notice: "Account Created"
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def edit
  end

  private

  helper_method :set_user
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :username,
        :email,
        :password,
        :bio,
        :profile_picture,
        :created_on
        )
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <!-- HEADER -->

  <head>
    <div class="header-content">
      <title>Jobs - Keeping you organized during your job search.</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      <!-- NAVIGATION -->

      <nav class="navigation">
        <ul class="navigation-links" style="list-style-type: none;">

          <li class="navigation-logo">
            <%= link_to "JOBS", root_path %>
          </li>

          <li class="navigation-page">
            <%= link_to "HOME", root_path %>
          </li>

          <% if current_user %>
              <li class="navigation-page">
                <%= link_to "DASHBOARD", user_leads_url(session[:user_id]) %>
              </li>

              <li class="navigation-page">
                <%= link_to "ACCOUNT", user_path(current_user) %>
              </li>

            <li class="navigation-page-session">
              <%= link_to "LOGOUT", signout_path, method: :delete %>
            </li>

          <% else %>
            <li class="navigation-page-session">
              <%= link_to "SIGN IN", signin_path%>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
    <hr>
  </head>

  <!-- BODY -->

  <body>
    <div class="body-content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/leads/_form.html.erb
<!-- FORM - NEW LEAD -->

<div class="form">
  <%= form_for [@user, @lead] do |f| %>

<!-- ERRORS -->

  <div class="error">
    <% if @lead.errors.any? %>

      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @lead.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

<!-- COMPANY INFORMATION -->

    <%= f.hidden_field :user_id %>

        <label>Existing Company:</label><br>
        <%= f.collection_select(:company_id, @user.companies.all.uniq, :id, :name, include_blank: 'Select an existing Company or make a new one below') %>
        <br>
        <br>
      <%= f.fields_for :company, @company do |company_field| %>

        <label>New Company:</label><br>
        <%= company_field.text_field :name %><br>

        <label>Description</label><br>
        <%= company_field.text_field :description %><br>

        <label>Website</label><br>
        <%= company_field.text_field :website %><br>

        <label>City</label><br>
        <%= company_field.text_field :city %><br>

      <% end %>
      <br>
      <br>

<!-- POSITION INFORMATION -->

    <label>Position</label><br>
    <%= f.text_field :position %><br>

    <label>Point Person</label><br>
    <%= f.text_field :point_person %><br>

    <label>Email</label><br>
    <%= f.email_field :email %><br>

    <label>Phone Number</label><br>
    <%= f.text_field :phone_number %><br>

    <label>Status</label><br>
    <%= f.select :status, Lead.options %><br>


    <%= f.submit class: "submit_button"  %>
  <% end %>
</div>

app/views/leads/edit.html.erb
<!-- FORM - EDIT LEAD -->

<h1>Edit Lead!</h1>

  <%= render 'form' %>

<!-- DELETE LEAD -->
  <p class="subtext">
    <%= link_to "Delete Lead", [@user, @lead], :method => :delete %>
  </p>

app/views/leads/index.html.erb
<!-- DASHBOARD -->

<h1>Dashboard</h1>

  <div class="button-large">
    <%= link_to "New Lead", new_user_lead_url(@user), class: "home_button" %>
  </div>
<!-- FILTER LEADS -->

<% if false %>
  <div class="filter">
    <% if !params[:status].blank? %>
      <% @leads = Lead.where(status: params[:status]) %>
    <% end %>

    <h3>Filter Leads:</h3>
      <%= form_tag(user_leads_url(@user), method: "get") do %>
        <%= select_tag :status, options_for_select([['Warm', 1],['Cold', 2]]), :include_blank => 'All' %>
        <%= submit_tag "Filter", class: "submit_button"  %>
      <% end %>
  </div>
<% end %>

<!-- LEADS -->

  <h2>Leads:</h2>
    <div class="table">
      <table>

  <!-- TABLE HEADER -->

          <tr class="table-header">
            <th>COMPANY</th>
            <th>WEBSITE</th>
            <th>CITY</th>
            <th>POSITION</th>
            <th>CONTACT PERSON</th>
            <th>PHONE NUMBER</th>
            <th>EMAIL</th>
            <th>STATUS</th>
            <th>EDIT</th>
          </tr>

  <!-- TABLE ROWS -->

        <% current_user.leads.each do |lead| %>
          <tr class="table-data">
            <td><%= Company.find_by(id: lead.company_id).name %></td>
            <td><%= Company.find_by(id: lead.company_id).website  %></td>
            <td><%= Company.find_by(id: lead.company_id).city %></td>
            <td><%= lead.position %></td>
            <td><%= lead.point_person %></td>
            <td><%= lead.phone_number %></td>
            <td><%= lead.email %></td>
            <td>
              <% if lead.status == "1" %>
                <%= "Warm" %>
              <% else %>
                <%= "Cold" %>
              <% end %>
            </td>
            <td><%= link_to "Edit Lead", edit_user_lead_url(@user, lead) %></td>
          </tr>
        <% end %>

      </table>
    </div>

app/views/leads/new.html.erb
<!-- FORM - NEW LEAD -->

<h1>New Lead!</h1>

  <%= image_tag('compressed/coffee_meeting_c.jpg', :class => "image_new_lead") %>

  <%= render 'form' %>

app/views/leads/search.erb
<% form_tag('/search') %>



<div class="table">
  <table>

<!-- TABLE HEADER -->

      <tr class="table-header">
        <th>COMPANY</th>
        <th>WEBSITE</th>
        <th>CITY</th>
        <th>POSITION</th>
        <th>CONTACT PERSON</th>
        <th>PHONE NUMBER</th>
        <th>EMAIL</th>
        <th>STATUS</th>
        <th>EDIT</th>
      </tr>

<!-- TABLE ROWS -->

    <% @leads.each do |lead| %>
      <tr class="table-data">
        <td><%= Company.find_by(id: lead.company_id).name %></td>
        <td><%= Company.find_by(id: lead.company_id).website  %></td>
        <td><%= Company.find_by(id: lead.company_id).city %></td>
        <td><%= lead.position %></td>
        <td><%= lead.point_person %></td>
        <td><%= lead.phone_number %></td>
        <td><%= lead.email %></td>
        <td>
          <% if lead.status == "1" %>
            <%= "Warm" %>
          <% else %>
            <%= "Cold" %>
          <% end %>
        </td>
        <td><%= link_to "Edit Lead", edit_user_lead_url(@user, lead) %></td>
      </tr>
    <% end %>

  </table>

app/views/leads/web_dev.erb
<h1> Web Dev Leads! </h1>


<% # bring in all the user LEADS %>

<div class="table">
  <table>

<!-- TABLE HEADER -->

      <tr class="table-header">
        <th>COMPANY</th>
        <th>WEBSITE</th>
        <th>CITY</th>
        <th>POSITION</th>
        <th>CONTACT PERSON</th>
        <th>PHONE NUMBER</th>
        <th>EMAIL</th>
        <th>STATUS</th>
        <th>EDIT</th>
      </tr>

<!-- TABLE ROWS -->

    <% current_user.leads.web_dev.each do |lead| %>
      <tr class="table-data">
        <td><%= Company.find_by(id: lead.company_id).name %></td>
        <td><%= Company.find_by(id: lead.company_id).website  %></td>
        <td><%= Company.find_by(id: lead.company_id).city %></td>
        <td><%= lead.position %></td>
        <td><%= lead.point_person %></td>
        <td><%= lead.phone_number %></td>
        <td><%= lead.email %></td>
        <td>
          <% if lead.status == "1" %>
            <%= "Warm" %>
          <% else %>
            <%= "Cold" %>
          <% end %>
        </td>
        <td><%= link_to "Edit Lead", edit_user_lead_url(@user, lead) %></td>
      </tr>
    <% end %>

  </table>



<% #call the scope method on those %>

<% #print those out %>

app/views/static_pages/home.html.erb
<!-- HOME -->

<h1 class="home_title">Keeping you organized during your job search.</h1>

<%= image_tag('home_images@2x.png', :class => "image_home") %>

<!-- BUTTONS -->
  <ul class="home_buttons">
    <% if current_user %>
      <div class="button-large" id="signup">
        <%= link_to "Dashboard", user_leads_url(session[:user_id]), class: "home_button"  %>
      </div>

    <% else %>
      <li><%= link_to "Sign up with Email", new_user_path, class: "home_button" %></li>
      <li><%= link_to(image_tag("github-login.png", class: "github"), '/auth/github') %></li>
  </ul>
<% end %>

app/views/users/_form.html.erb
<!-- FORM - NEW USER -->

<div class="form">
  <%= form_for @user do |f| %>

<!-- ERRORS -->

  <div class="error">
    <% if @user.errors.any? %>
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>
    <div class="error-list">
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
    <% end %>
  </div>

<!-- USER INFORMATION -->

    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
    <br>

    <%= f.submit class: "submit_button" %>

  <% end %>

app/views/users/edit.html.erb
<!-- FORM - EDIT USER -->

<h1>Edit Account</h1>

  <%= render 'form' %>

app/views/users/new.html.erb
<!-- FORM - NEW USER -->

<h1>Create an account!</h1>
  <p class="subtext">
    Already have an account? <%= link_to "Sign In", signin_path %>
  </p>

  <%= render 'form' %>

app/views/users/show.html.erb
<!-- SHOW - USER -->

<h1> Account: <%= @user.username.upcase %> </h1>
  <%= link_to "Update Account Details", edit_user_path(@user) %>

  <p> Member Since: <%= @user.created_on.strftime("%B, %Y") %> </p>

  <%= @user.bio %>